[package]
name = "grimoire"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
clap = { version = "4.5.42", features = ["derive"] }
comrak = "0.40.0"
rust-embed = "8.7.2"
tera = "1.20.0"
time-util = "0.3.4"
tokio = { version = "1.47.0", features = ["full"] }
