[package]
name = "grimoire"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.47.0", features = ["full"] }
